version: "3"
services:

 model-service:
    image: "backend-new:latest"
    ports:
      - "8000:8000"

 app:
    depends_on:
      - model-service
    image: "frontend-new:latest"
    ports:
      - "3000:3000"

