version: "3"
services:

 model-service:
    image: "ghcr.io/remla23-team13/model-service:0.0.latest"
    ports:
      - "8000:8000"
#    volumes:
#      - ./volumes/main.py:/root/main.py

 app:
   image: "ghcr.io/remla23-team13/app:0.0.latest"
   ports:
     - "3000:3000"
   depends_on:
     - model-service
   environment:
     - REACT_APP_API_URL=http://localhost:8000/predict