version: "3"
services:

 model-service:
    image: ghcr.io/remla23-team13/model-service:latest
    ports:
      - "8000:8000"

 app:
    image: ghcr.io/remla23-team13/app:latest
    ports:
      - "3000:3000"

