version: "3"
services:

 model-service:
    image: ghcr.io/remla23-team13/model-service:latest
    ports:
      - "8080:8000"


 app:
    image: ghcr.io/remla23-team13/app:latest
    ports:
      - "8000:3000"

