apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: my-ingress
spec:
  rules:

     - http:
        paths:
        {{- with $.Values.webapp }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .service.name }}
                port:
                  number: {{ .port }}
        {{- end }}

        {{- with $.Values.modelService }}
          - path: /model-s-service/.*
            pathType: Prefix
            backend:
              service:
                name: {{ .service.name }}
                port:
                  number: {{ .port }}
        {{- end }}

    # {{- with $.Values.grafana }}
    #  - host: {{ .host }}
    #    http:
    #      paths:
    #      - path: /
    #        pathType: Prefix
    #        backend:
    #          service:
    #            name: "{{  $.Release.Name }}-grafana"
    #            port:
    #              number: {{ .port }}
    #    {{- end }}