apiVersion: apps/v1
kind: Deployment
{{- with $.Values.modelService }}
metadata:
  name: "{{ .deploymentName }}"
  labels:
    app: {{ .deploymentName }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .deploymentName }}
    spec:
      containers:
        - name: {{ .deploymentName }}
          image: "ghcr.io/remla23-team13/model-service:{{ .tag }}"
          ports:
            - name: "{{ .portName }}"
              containerPort: {{ .port }}
          volumeMounts:
            - mountPath: /root/main.py
              name: my-volume
          env:
            - name: MODEL_PATH
              value: {{ .modelPath }}
            - name: MODEL_URL
              value: {{ .modelUrl }}
            - name: MODEL_FILE
              value: {{ .modelFile }}
            - name: PREPROCESSOR_URL
              value: {{ .preprocessorUrl }}
            - name: PREPROCESSOR_FILE
              value: {{ .preprocessorFile }}
      volumes:
        - name: my-volume
          hostPath:
            path: ./volumes/main.py
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .service.name }}"
  labels:
    app: "{{ .service.name }}"
spec:
  selector:
    app: {{ .deploymentName }}
  ports:
    - name: "{{ .portName }}"
      port: {{ .port }}
      targetPort: {{ .port }}
{{- end }}