{{- with $.Values.modelService }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: model-service-configmap
data:
  model-url: "{{ .modelUrl }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: model-service-secret
data:
  model-file: "{{ .modelFileEncoded }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .deploymentName }}"
  labels:
    app: {{ .deploymentName }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .deploymentName }}
    spec:
      containers:
        - name: {{ .deploymentName }}
          image: "ghcr.io/remla23-team13/model-service:{{ .tag }}"
          ports:
            - name: "{{ .portName }}"
              containerPort: {{ .port }}

          env:
            - name: MODEL_URL
              valueFrom:
                configMapKeyRef:
                  name: model-service-configmap
                  key: model-url
            - name: MODEL_FILE
              valueFrom:
                secretKeyRef:
                  name: model-service-secret
                  key: model-file
            - name: PREPROCESSOR_URL
              value: {{ .preprocessorUrl }}
            - name: PREPROCESSOR_FILE
              value: {{ .preprocessorFile }}
          volumeMounts:
            - mountPath: {{ .volume.mountPath }}
              name: {{ .volume.name }}
      volumes:
        - name: {{ .volume.name }}
          hostPath:
            path: {{ .volume.hostPath }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .service.name }}"
  labels:
    app: "{{ .service.name }}"
spec:
  selector:
    app: {{ .deploymentName }}
  ports:
    - name: "{{ .portName }}"
      port: {{ .port }}
      targetPort: {{ .port }}
{{- end }}