apiVersion: apps/v1
kind: Deployment
{{- with .Values.webapp }}
metadata:
  name: "{{ .name }}-deployment"
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers: 
        - name: {{ .name }}
          image: "ghcr.io/remla23-team13/app:{{ .tag }}"
          ports:
            - containerPort: {{ .port }}
          env:
            - name: REACT_APP_API_MODEL_PATH
              value: "/model-s-service"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .service.name }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
  type: ClusterIP
{{- end }}


