modelService:
  name: model-s
  replicas: 1
  tag: latest
  port: 8000
  modelPath: /model-s-service
  modelUrl: https://drive.google.com/uc?id=1Ykfy1Eq_k3jZgLjGuzt5QI5_1T6NYrDO&export=download
  modelFile: model.joblib
  preprocessorUrl: https://drive.google.com/uc?id=1Ud_w0xAmpg6xfUX30DO6cGFSWX5hU3Qr&export=download
  preprocessorFile: preprocessor.joblib
  service:  
    name: model-s-service

webapp:
  name: webapp
  replicas: 1
  tag: latest
  port: 3000
  service:
    name: webapp-service 

monitoring:
  name: monitoring-service-monitor

kube-prometheus-stack: 
  prometheus:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /$2
      paths: ["/prometheus(/|$)(.*)"]

  grafana:
    env:
      GF_SERVER_ROOT_URL: https://localhost:80/grafana
      GF_SERVER_SERVE_FROM_SUB_PATH: 'true'
    # username is 'admin'
    adminPassword: prom-operator
    defaultDashboardsEnabled: false
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /$2
      path: "/grafana(/|$)(.*)"
  
