apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-entry-service
spec:
  gateways:
    - my-istio-gateway
  hosts:
    - "*"
  http:
    - match:
        - uri:
            regex: /model-s-service/.*
          sourceLabels:
            version: v2
#      route:
#        - destination:
#            host: model-s
#        - sourceLabels:
#            version: v2
      route:
        - destination:
            host: model-s
            subset: v2
#    - route:
        - destination:
            host: model-s
            subset: v1
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: webapp
            subset: v1
          weight: 50
        - destination:
            host: webapp
            subset: v2
          weight: 50
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata:
#  name: model-s
#spec:
#  gateways:
#    - my-istio-gateway
#  hosts:
#    - "model.example.com"
#  http:
#    - match:
#        - uri:
#            regex: /model-s-service/.*
#        - sourceLabels:
#            version: v2
#      route:
#        - destination:
#            host: model-s
#            subset: v2
#    - route:
#        - destination:
#            host: model-s
#            subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-istio-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"