apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webapp-virtual-service
spec:
  gateways:
    - istio-gateway
  hosts:
    - "*"
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: webapp-service
            subset: v1
          weight: 50 
        - destination:
            host: webapp-service
            subset: v2
          weight: 50 
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: model-virtual-service
spec:
  hosts:
    - model-service
  http:
    - match:
        - sourceLabels:
            version: v2
      route:
        - destination:
            host: model-service
            subset: v2
    - route:
        - destination:
            host: model-service
            subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
