apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-s-deployment-v1
  labels: {app: model-s, version: v1}
spec:
  replicas: 1
  selector:
    matchLabels: {app: model-s, version: v1}
  template:
    metadata:
      labels: {app: model-s, version: v1}
    spec:
      containers:
        - name: model-s
          image: ghcr.io/remla23-team13/model-service:0.latest
          imagePullPolicy: Always
          ports:
            - name: model-s-port
              containerPort: 8000
          env:
            - name: MODEL_PATH
              value: /model-s-service
---
apiVersion: v1
kind: Service
metadata:
  name: model-s
spec:
  type: NodePort
  selector:
    app: model-s
  ports:
    - port: 8000
      targetPort: 8000