apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-v1
  labels: {app: webapp-deployment, version: v1}
spec:
  replicas: 1
  selector:
    matchLabels: {app: webapp-deployment, version: v1}
  template:
    metadata:
      labels: {app: webapp-deployment, version: v1}
    spec:
      containers:
        - name: webapp-deployment
          image: ghcr.io/remla23-team13/app:2.0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MODEL_SERVICE_URL
              value: http://model-service:8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-v2
  labels: {app: webapp-deployment, version: v2}
spec:
  replicas: 1
  selector:
    matchLabels: {app: webapp-deployment, version: v2}
  template:
    metadata:
      labels: {app: webapp-deployment, version: v2}
    spec:
      containers:
        - name: webapp-deployment
          image: ghcr.io/remla23-team13/app:2.0.4
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MODEL_SERVICE_URL
              value: http://model-service:8000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp-deployment
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: webapp-service-rule
spec:
  host: webapp-service
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
