apiVersion: apps/v1
kind: Deployment
metadata:
  name: "webapp-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers: 
        - name: webapp
          image: "ghcr.io/remla23-team13/app:2.0.0"
          ports:
            - containerPort: 3000
          env:
            - name: MODEL_SERVICE_URL
              value: "http://model-service:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
    - port: 3000
      targetPort: 3000


