{
 "title": "WHOOP",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Ratio of wrong predictions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wrong_prediction_ratio{webapp=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of predictions over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(num_requests[$__rate_interval])",
     "legendFormat": "prediction rate"
    }
   ]
  },
  {
   "title": "Review size",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "review_size_bucket", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Average review size in the last 24 hours",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(review_size_sum{}[1d])/last_over_time(review_size_count{}[1d])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}